services:
  neo4j:
    restart: unless-stopped

  web:
    restart: unless-stopped

  nginx:
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.aws.conf:/etc/nginx/nginx.conf:ro
      - ./internal/public:/var/www/html:ro
      - ./static:/var/www/static:ro
      - uploads:/var/www/uploads:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
