services:
  neo4j:
    ports:
      - "7474:7474"
      - "7687:7687"

  nginx:
    ports:
      - "8081:80"
    volumes:
      - ./nginx.local.conf:/etc/nginx/nginx.conf:ro
      - ./internal/public:/var/www/html:ro
      - ./static:/var/www/static:ro
      - uploads:/var/www/uploads:ro
